### PR TITLE
updated to current Swift Package Manager preprocessor

### PR DESCRIPTION
**Pull request by yoiang**
I was unable to find mention of the preprocessor `SWIFT_PACKAGE_MANAGER` or get it to work in its current form. The [Create a Package](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#create-a-package) section of the Swift Package Manager documentation instead suggests the preprocessor `SWIFT_PACKAGE` for this usage.

### CODE REVIEW

**Comment by emaloney** [comment]
This project is now deprecated as a result of Apple's deprecation of the ASL subsystem.

Closing pull request.

**Comment by yoiang** [comment]
@emaloney gotcha! Is CleanroomLogger being updated to no longer use ASL?

**Comment by emaloney** [comment]
Yes, that work is pending.

**Comment by emaloney** [comment]
An update: The removal of CleanroomASL from CleanroomLogger is nearly complete and will be released in the near future. In the meantime, you can track the work via [the `asl-free` branch](https://github.com/emaloney/CleanroomLogger/tree/asl-free).

**Comment by yoiang** [comment]
🚀 thanks dude!

**Pull request closed without merging**
